server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  #Database
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: peoplein

  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

